### ISSUE TITLE
Add reference links?

### ISSUE THREAD

**Issue by ajb** [benbalter/government-glossary#3]
It would be neat if SAM linked to sam.gov, FEDRamp linked to http://cloud.cio.gov/fedramp, etc. Sometimes finding the best place to link to is hard, so if this glossary included these links, it would be valuable for folks like me, who already know the acronym but struggle to find the authoritative source for more information.

**Comment by benbalter** [comment]
Definitions support markdown. Added a few in b5d4460, also [a note](https://github.com/benbalter/government-glossary/blob/gh-pages/CONTRIBUTING.md#style) in `CONTRIBUTING.md` to add where possible.

**Comment by ajb** [comment]
Awesome, thanks for incorporating :)
